module.exports = {
  endOfLine: "lf",
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^~shared/(.*)$",
    "^~assets/(.*)$",
    "^~contexts/(.*)$",
    "^~constants/(.*)$",
    "^~components/(.*)$",
    "^~templates/(.*)$",
    "^~features/(.*)$",
    "^~hooks/(.*)$",
    "^~utils/(.*)$",
    "^~pages/(.*)$",
    "^~services/(.*)$",
    "^~typings/(.*)$",
    "^~/(.*)$",
    "",
    "^[./]",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
};
