package io.mosip.signup.util;

public class ErrorConstants {
    public static final String CHALLENGE_FAILED = "challenge_failed";
    public static final String INVALID_CHALLENGE_INFO = "invalid_challenge_info";
    public static final String INVALID_IDENTIFIER = "invalid_identifier";
    public static final String INVALID_USERNAME = "invalid_username";
    public static final String INVALID_PASSWORD = "invalid_password";
    public static final String INVALID_USERINFO = "invalid_username";
    public static final String INVALID_CONSENT = "invalid_consent";
    public static final String IDENTIFIER_MISMATCH = "identifier_mismatch";
    public static final String CONSENT_REQUIRED = "consent_required";
    public static final String INVALID_TRANSACTION="invalid_transaction";
    public static final String UNSUPPORTED_CHALLENGE_TYPE ="unsupported_challenge_type";
    public static final String INVALID_CAPTCHA="invalid_captcha";
    public static final String GENERATE_CHALLENGE_FAILED ="generate_challenge_failed";
    public static final String UNKNOWN_ERROR="unknown_error";
    public static final String TOO_MANY_ATTEMPTS="too_many_attempts";
    public static final String INVALID_REQUEST="invalid_request";
    public static final String INVALID_CHALLENGE="invalid_challenge";
    public static final String CHALLENGE_EXPIRED="challenge_expired";
    public static final String INVALID_CHALLENGE_FORMAT="invalid_challenge_format";
    public static final String INVALID_CHALLENGE_TYPE="invalid_challenge_type";
    public static final String INVALID_PHONE_NUMBER = "invalid_phone_number";
    public static final String UNSUPPORTED_LANGUAGE = "unsupported_language";
    public static final String INVALID_VALUE = "invalid_value";
    public static final String ADD_IDENTITY_FAILED = "add_identity_failed";
    public static final String RESET_PWD_FAILED = "reset_pwd_failed";
    public static final String HASH_GENERATE_FAILED = "hash_generate_failed";
    public static final String GET_UIN_FAILED = "get_uin_failed";
    public static final String INVALID_FULLNAME = "invalid_fullname";
    public static final String TOO_EARLY_ATTEMPT = "too_early_attempt";
    public static final String UNSUPPORTED_PURPOSE = "unsupported_purpose";
    public static final String IDENTIFIER_ALREADY_REGISTERED = "identifier_already_registered";
    public static final String IDENTIFIER_NOT_FOUND = "identifier_not_found";
    public static final String INVALID_KBA_CHALLENGE = "invalid_KBA_challenge";
    public static final String KBA_CHALLENGE_NOT_FOUND = "kba_challenge_not_found";
    public static final String IDENTITY_INACTIVE = "identity_inactive";
    public static final String FETCH_IDENTITY_FAILED = "fetch_identity_failed";
    public static final String CHALLENGE_FORMAT_AND_TYPE_MISMATCH = "challenge_format_and_type_mismatch";
    public static final String KNOWLEDGEBASE_MISMATCH = "knowledgebase_mismatch";
    public static final String IDENTIFIER_BLOCKED = "identifier_blocked";
}
