services:
  database:
    image: 'postgres:bookworm'
    ports:
      - 5455:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mock-identity-system:
    image: 'mosipdev/mock-identity-system:develop'
    user: root
    ports:
      - 8082:8082
    environment:
      - container_user=mosip
      - active_profile_env=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mosip_mockidentitysystem?currentSchema=mockidentitysystem
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - database

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  esignet:
    image: 'mosipdev/esignet:develop'
    user: root
    ports:
      - 8088:8088
    environment:
      - container_user=mosip
      - active_profile_env=local
      - plugin_name_env=esignet-mock-plugin.jar
      - KAFKA_ENABLED=false
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mosip_esignet?currentSchema=esignet
      - SPRING_CACHE_TYPE=simple
      - MOSIP_ESIGNET_MOCK_DOMAIN_URL=http://mock-identity-system:8082
    depends_on:
      - database
      - mock-identity-system

  esignet-ui:
    image: 'mosipdev/oidc-ui:develop'
    user: root
    ports:
      - 3000:3000
    environment:
      - container_user=mosip
      - DEFAULT_WELLKNOWN=%5B%7B%22name%22%3A%22OpenID%20Configuration%22%2C%22value%22%3A%22%2F.well-known%2Fopenid-configuration%22%7D%2C%7B%22name%22%3A%22Jwks%20Json%22%2C%22value%22%3A%22%2F.well-known%2Fjwks.json%22%7D%2C%7B%22name%22%3A%22Authorization%20Server%22%2C%22value%22%3A%22%2F.well-known%2Foauth-authorization-server%22%7D%5D
      - SIGN_IN_WITH_ESIGNET_PLUGIN_URL=https://raw.githubusercontent.com/mosip/artifactory-ref-impl/master/artifacts/src/mosip-plugins/sign-in-with-esignet/sign-in-with-esignet.zip
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - esignet

  signup:
    image: 'mosipdev/signup-service:develop'
    user: root
    ports:
      - 8089:8089
    environment:
      - container_user=mosip
      - active_profile_env=local
      - plugin_name_env=esignet-mock-plugin.jar
      - MOSIP_ESIGNET_MOCK_DOMAIN_URL=http://mock-identity-system:8082
    depends_on:
      - database
      - mock-identity-system