apiVersion: v1
entries:
  common:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 1.17.1
    created: "2023-12-05T10:52:28.791683171+05:30"
    description: A Library Helm Chart for grouping common logic between bitnami charts.
      This chart is not deployable by itself.
    digest: 2a623d42475796af0ff0d18bbfa3b76ead1ccd7efab8280ea079b6a53f5ac627
    home: https://github.com/bitnami/charts/tree/master/bitnami/common
    icon: https://bitnami.com/downloads/logos/bitnami-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - bitnami
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: common
    sources:
    - https://github.com/bitnami/charts
    - https://www.bitnami.com/
    type: library
    urls:
    - charts/common-1.17.1.tgz
    version: 1.17.1
generated: "2023-12-05T10:52:28.790727051+05:30"
