SignUpSettings:
   Signup_ESignet_SignUpSettings_Valid_smoke_Pos:
      endPoint: /v1/signup/settings
      role: resident
      restMethod: post
      checkErrorsOnlyInResponse: true
      inputTemplate: signup/SignUpSettings/SignUpSettings
      outputTemplate: signup/SignUpSettings/SignUpSettingsResult
      input: '{
}'
      output: '{
}'